### ISSUE TITLE
Wrong argv str passed to `parse_args()` method in `__main__.py`

### ISSUE THREAD

**Issue by mo-han** [gebn/beam#5]
I just installed beam by pip and found the command-line tool `beam` malfunctioning. It simply cannot take the `host` argument I gave. I spent some time and found out the cause.

in `beam/__main__.py`, the arguments are parsed like this:
```python
def _parse_args(argv):
    ...
    return parser.parse_args(argv)

...
args = _parse_args(sys.argv)
...
```
As you can see the whole `sys.argv` is passed to `_parse_args()`. The problem is, `sys.argv` includes the exec `beam` itself. So `sys.argv[0]` might be something like `/home/xxx/.py3/bin/beam`, which will be parsed as `host`, while the real host argument is behind it at `sys.argv[1]` and of course ignored. Then it would never get the correct `host` argument.

IMHO, nothing needs to be passed to `parse_args()`, which is:
```python
def _parse_args():
    ...
    return parser.parse_args()

...
args = _parse_args()
...
```

By default `parse_args()` method requires no args, it automatically takes the needed argv str from `sys.argv`, eg. `sys.argv[1:]`, to parse. However, if we explicitly give it a str to parse, we need to make sure the str is a good one, `sys.argv` is no good.

**Comment by gebn** [comment]
Hi @mo-han, thanks for the well-written bug report! I'm in favour of explicitly passing the list of arguments to `_parse_args()`, as this makes it much easier to test the function. I've committed 2365833, which chops the command off the front of the argument list before passing it to `argparse`, and released 0.5.0 so you can simply update your local install to get the fix.
